apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-deployment
spec:
  selector:
    matchLabels:
      app: my-flask-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: my-flask-pod
    spec:
      containers:
      - name: my-flask-container
        image: yusufkaratoprak/awsflaskeks:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000