apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-flask
spec:
  selector:
    matchLabels:
      app: my-flask
  replicas: 2
  template:
    metadata:
      labels:
        app: my-flask
    spec:
    containers:
        - name: my-flask
          image: yusufkaratoprak/awsflaskeks:latest
          ports:
            - containerPort: 5000